apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: producer-state
  namespace: weather-dev
  labels:
    app.kubernetes.io/name: weather-producer
    app.kubernetes.io/component: producer
    app.kubernetes.io/part-of: weather-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
