apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
data:
  POSTGRES_PORT: "5434"
  POSTGRES_DB: weather_db_python_dev
  KAFKA_TOPIC: raw_weather_events_python_dev
  KAFKA_CLIENT_ID: weather-producer-python-dev
  KAFKA_CONSUMER_GROUP: weather-postgres-consumer-python-dev
