apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
data:
  POSTGRES_PORT: "5433"
  POSTGRES_DB: weather_db_dev
  KAFKA_TOPIC: raw_weather_events_python_prod
  KAFKA_CLIENT_ID: weather-producer-python-prod
  KAFKA_CONSUMER_GROUP: weather-postgres-consumer-python-prod
