apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-prod-python

resources:
  - ../../kubernetes
  - namespace.yaml

patches:
  - path: configmap-patch.yaml
  - path: kafka-patch.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: production
    includeSelectors: false
