apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-python

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres/service.yaml
  - kafka/service.yaml
  - kafka/statefulset.yaml
  - reconciler/cronjob.yaml
  - producer/deployment.yaml
  - consumer/deployment.yaml
  - aggregator/deployment.yaml
  - api/service.yaml
  - api/deployment.yaml
  - dashboard/service.yaml
  - dashboard/deployment.yaml
  - kafka-ui/service.yaml
  - kafka-ui/deployment.yaml
  - monitoring/prometheus-rbac.yaml
  - monitoring/prometheus-config.yaml
  - monitoring/prometheus.yaml
  - monitoring/kube-state-metrics.yaml
  - monitoring/grafana-config.yaml
  - monitoring/grafana.yaml
